import type { Metadata } from 'next';
import { stegaClean } from 'next-sanity';
import { type Locale, routing } from '@/i18n/routing';
import { BASE_URL, isPreview, isStaging, vercelPreview } from './env';
import resolveUrl from './resolveUrl';

// Generate hreflang alternate URLs for all supported locales
function generateAlternateLanguages(
  page: Sanity.PageBase,
  translations?: Array<{ slug: string; language: string; _type: string }>
): Record<string, string> {
  const alternates: Record<string, string> = {};
  const defaultLocale = routing.defaultLocale;
  const locales = routing.locales as Locale[];

  for (const locale of locales) {
    // Check if there's a translation for this locale (filter out null items)
    const translation = translations?.filter(Boolean).find((t) => t.language === locale);

    if (translation) {
      // Use the translation's slug
      const langPrefix = locale === defaultLocale ? '' : `/${locale}`;
      const pathSegment = translation._type === 'blog.post' ? '/blog' : '';
      const slugPath = translation.slug === 'index' ? '' : `/${translation.slug}`;
      alternates[locale] = `${BASE_URL}${langPrefix}${pathSegment}${slugPath}`;
    } else if (locale === page.language) {
      // Current page's locale
      alternates[locale] = resolveUrl(page, { base: true });
    }
  }

  // Add x-default pointing to the default locale version
  if (alternates[defaultLocale]) {
    alternates['x-default'] = alternates[defaultLocale];
  }

  return alternates;
}

export default async function processMetadata(
  page: (Sanity.Page | Sanity.BlogPost | Sanity.ComponentLibrary) & {
    translations?: Array<{ slug: string; language: string; _type: string }>;
  },
  searchParams?: Record<string, string | string[] | undefined>
): Promise<Metadata> {
  if (!page.metadata) {
    throw new Error('Page metadata is required');
  }

  const url = resolveUrl(page as Sanity.PageBase, {
    params: searchParams,
    allowList: ['page', 'category'],
  });
  const { title, description, ogimage: uploadedOg, noIndex } = page.metadata;

  // Clean metadata values for SEO and browser display
  const cleanTitle = stegaClean(title);
  const cleanDescription = stegaClean(description);
  const autogeneratedOg = `${BASE_URL}/api/og?title=${encodeURIComponent(cleanTitle)}`;

  let metadataBase: URL | undefined;
  try {
    metadataBase = new URL(BASE_URL);
  } catch (_error) {
    // Fallback to localhost if BASE_URL is invalid during build
    metadataBase = new URL('http://localhost:3000');
  }

  return {
    metadataBase,
    title: cleanTitle,
    description: cleanDescription,
    openGraph: {
      type: page._type === 'blog.post' ? 'article' : 'website',
      url,
      title: cleanTitle,
      description: cleanDescription,
      images: uploadedOg || autogeneratedOg,
      ...(page._type === 'blog.post' && {
        publishedTime: (page as Sanity.BlogPost).publishDate,
      }),
    },
    robots: {
      index: noIndex || vercelPreview || isStaging || isPreview ? false : undefined,
    },
    alternates: {
      canonical: url,
      languages: generateAlternateLanguages(page, page.translations),
      types: {
        'application/rss+xml': '/blog/rss.xml',
      },
    },
    twitter: {
      card: 'summary_large_image',
    },
  };
}
