import type { Metadata } from 'next';
import { stegaClean } from 'next-sanity';
import { BASE_URL, isPreview, isStaging, vercelPreview } from './env';
import resolveUrl from './resolveUrl';

export default async function processMetadata(
  page: Sanity.Page | Sanity.BlogPost | Sanity.ComponentLibrary,
  searchParams?: Record<string, string | string[] | undefined>
): Promise<Metadata> {
  if (!page.metadata) {
    throw new Error('Page metadata is required');
  }

  const url = resolveUrl(page as Sanity.PageBase, {
    params: searchParams,
    allowList: ['page', 'category'],
  });
  const { title, description, ogimage: uploadedOg, noIndex } = page.metadata;

  // Clean metadata values for SEO and browser display
  const cleanTitle = stegaClean(title);
  const cleanDescription = stegaClean(description);
  const autogeneratedOg = `${BASE_URL}/api/og?title=${encodeURIComponent(cleanTitle)}`;

  let metadataBase: URL | undefined;
  try {
    metadataBase = new URL(BASE_URL);
  } catch (_error) {
    // Fallback to localhost if BASE_URL is invalid during build
    metadataBase = new URL('http://localhost:3000');
  }

  return {
    metadataBase,
    title: cleanTitle,
    description: cleanDescription,
    openGraph: {
      type: page._type === 'blog.post' ? 'article' : 'website',
      url,
      title: cleanTitle,
      description: cleanDescription,
      images: uploadedOg || autogeneratedOg,
      ...(page._type === 'blog.post' && {
        publishedTime: (page as Sanity.BlogPost).publishDate,
      }),
    },
    robots: {
      index: noIndex || vercelPreview || isStaging || isPreview ? false : undefined,
    },
    alternates: {
      canonical: url,
      types: {
        'application/rss+xml': '/blog/rss.xml',
      },
    },
    twitter: {
      card: 'summary_large_image',
    },
  };
}
