import type { Metadata } from 'next';
import { stegaClean } from 'next-sanity';
import { type Locale, routing } from '@/i18n/routing';
import { BASE_URL, isPreview, isStaging, vercelPreview } from '@/lib/core/env';
import resolveUrl from './resolve-url';

// Generate hreflang alternate URLs for all supported locales
function generateAlternateLanguages(
  page: Sanity.PageBase,
  translations?: Array<{ slug: string; language: string; _type: string }>
): Record<string, string> {
  const alternates: Record<string, string> = {};
  const defaultLocale = routing.defaultLocale;
  const locales = routing.locales as Locale[];

  for (const locale of locales) {
    // Check if there's a translation for this locale (filter out null items)
    const translation = translations?.filter(Boolean).find((t) => t.language === locale);

    if (translation) {
      // Use the translation's slug
      const langPrefix = locale === defaultLocale ? '' : `/${locale}`;
      const slugPath = translation.slug === 'index' ? '' : `/${translation.slug}`;
      alternates[locale] = `${BASE_URL}${langPrefix}${slugPath}`;
    } else if (locale === page.language) {
      // Current page's locale
      alternates[locale] = resolveUrl(page, { base: true });
    }
  }

  // Add x-default pointing to the default locale version
  if (alternates[defaultLocale]) {
    alternates['x-default'] = alternates[defaultLocale];
  }

  return alternates;
}

// SEO-specific fields (subset of Metadata without slug)
interface SeoFields {
  title?: string;
  description?: string;
  ogimage?: string;
  noIndex?: boolean;
}

// Article types that should use 'article' OpenGraph type
const ARTICLE_TYPES = ['collection.blog', 'collection.newsletter', 'collection.events'];

function getOpenGraphType(pageType: string): 'article' | 'website' {
  return ARTICLE_TYPES.includes(pageType) ? 'article' : 'website';
}

function getPublishedTime(
  page: Sanity.CollectionBlogPost | Sanity.CollectionNewsletter | Sanity.CollectionEvents | unknown
): string | undefined {
  if ((page as Sanity.CollectionBlogPost).publishDate) {
    return (page as Sanity.CollectionBlogPost).publishDate;
  }
  if ((page as Sanity.CollectionEvents).startDateTime) {
    return (page as Sanity.CollectionEvents).startDateTime;
  }
  return undefined;
}

function shouldNoIndex(noIndex?: boolean): boolean | undefined {
  if (noIndex || vercelPreview || isStaging || isPreview) {
    return false;
  }
  return undefined;
}

export default async function processMetadata(
  page: (
    | Sanity.Page
    | Sanity.ComponentLibrary
    | Sanity.CollectionBlogPost
    | Sanity.CollectionDocumentation
    | Sanity.CollectionEvents
    | Sanity.CollectionNewsletter
  ) & {
    seo?: SeoFields;
    translations?: Array<{ slug: string; language: string; _type: string }>;
  },
  searchParams?: Record<string, string | string[] | undefined>
): Promise<Metadata> {
  // Require either seo or metadata to be present
  if (!page.seo && !page.metadata) {
    throw new Error('Page SEO metadata is required');
  }

  const url = resolveUrl(page as Sanity.PageBase, {
    params: searchParams,
    allowList: ['page', 'category'],
  });

  // Prefer 'seo' field (new schema) over legacy 'metadata'
  const title = page.seo?.title || page.metadata?.title;
  const description = page.seo?.description || page.metadata?.description;
  const noIndex = page.seo?.noIndex ?? page.metadata?.noIndex;
  const uploadedOg = page.seo?.ogimage || page.metadata?.ogimage;

  // Clean metadata values for SEO and browser display
  const cleanTitle = stegaClean(title ?? '');
  const cleanDescription = stegaClean(description ?? '');
  const autogeneratedOg = `${BASE_URL}/api/og?title=${encodeURIComponent(cleanTitle)}`;

  let metadataBase: URL | undefined;
  try {
    metadataBase = new URL(BASE_URL);
  } catch (_error) {
    // Fallback to localhost if BASE_URL is invalid during build
    metadataBase = new URL('http://localhost:3000');
  }

  const publishedTime = getPublishedTime(page);

  return {
    metadataBase,
    title: cleanTitle,
    description: cleanDescription,
    openGraph: {
      type: getOpenGraphType(page._type),
      url,
      title: cleanTitle,
      description: cleanDescription,
      images: uploadedOg || autogeneratedOg,
      ...(publishedTime && { publishedTime }),
    },
    robots: {
      index: shouldNoIndex(noIndex),
    },
    alternates: {
      canonical: url,
      languages: generateAlternateLanguages(page as Sanity.PageBase, page.translations),
      types: {
        'application/rss+xml': '/blog/rss.xml',
      },
    },
    twitter: {
      card: 'summary_large_image',
    },
  };
}
