'use client';

import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';

type TableOfContentsProps = {
  headings: {
    style: string;
    text: string;
  }[];
};

export default function TableOfContents({ headings }: TableOfContentsProps) {
  const [activeId, setActiveId] = useState<string>('');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: '-100px 0px -66%' }
    );

    const headingElements = document.querySelectorAll('h2, h3');
    headingElements.forEach((element) => {
      observer.observe(element);
    });

    return () => {
      headingElements.forEach((element) => {
        observer.unobserve(element);
      });
    };
  }, []);

  if (!headings?.length) return null;

  return (
    <nav className="sticky top-24 max-h-[calc(100vh-6rem)] overflow-auto">
      <h4 className="mb-4 text-sm font-semibold tracking-tight text-foreground">On this page</h4>
      <ul className="space-y-2 text-sm">
        {headings.map((heading, index) => {
          // Create a slug from the heading text to match IDs generated by PortableText
          // This assumes the PortableText renderer generates IDs based on text content
          // If not, we'll need to update the PortableText components to add IDs
          const id = heading.text
            .toLowerCase()
            .replace(/[^\w\s-]/g, '')
            .replace(/\s+/g, '-');

          return (
            <li
              key={index}
              className={cn(
                'transition-colors hover:text-foreground',
                heading.style === 'h3' && 'pl-4',
                activeId === id ? 'font-medium text-foreground' : 'text-muted-foreground'
              )}
            >
              <a
                href={`#${id}`}
                onClick={(e) => {
                  e.preventDefault();
                  document.querySelector(`#${id}`)?.scrollIntoView({
                    behavior: 'smooth',
                  });
                }}
                className="block py-1"
              >
                {heading.text}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
