name: Validate Template
on: push

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Validate Sanity Template
        uses: sanity-io/template-validator@6f6003224268499e7361fa848b0c9eed232a2113 # v2
